### ISSUE TITLE
Is docker-compose install check necessary?

### ISSUE THREAD

**Issue by micaherne** [moodlehq/moodle-ci-runner#122]
I've just moved from the master branch to the new main one and am seeing a failure due to docker-compose not being installed: https://github.com/moodlehq/moodle-ci-runner/blob/main/runner/main/modules/docker/docker.sh#L34

I don't see anywhere that `docker-compose` is being called (or `docker compose`) so I was wondering if this could be removed?

**Comment by stronk7** [comment]
Hi @micaherne,

well spotted. I think that, when I started with the move to the new modular alternative (now in `main`) initially I had the idea of also using `docker compose` to be able to orchestrate everything similar to [moodle-docker](https://github.com/moodlehq/moodle-docker), but at the end I discarded that.

So, yes, I think that right now we don't need `docker compose` at all, so I'll proceed to remove the requirement soon.

Thanks!

**Comment by micaherne** [comment]
Thanks @stronk7!
