### ISSUE TITLE
Can't run @app tests if you dont have local_moodlemobileapp

### ISSUE THREAD

**Issue by marxjohnson** [moodlehq/moodle-ci-runner#50]
We recently spotted our job to run our mobile app tests was not running anything.
On investigation, I found this commit: https://github.com/moodlehq/moodle-ci-runner/commit/4f0487876f9528923747c58688a1fa54a49aa795

This is fine if you're running app tests for core plugins that live in local_moodlemobileapp, but we're trying to run tests tagged @app in the tests/behat directories of our own plugins. This is easily worked around by creating a fake plugins/local/moodlemobileapp directroy and setting PLUGINSDIR, but it seems uncessary when you can just set MOBILE_VERSION to a blank string if you don't want to run the ionic container.

**Comment by crazyserver** [comment]
Hi @marxjohnson I think this has been solved in this commit: https://github.com/moodlehq/moodle-ci-runner/commit/f977d82b966d0b1ac76b7fdb2f3f08e9c29335d6

**Comment by NoelDeMartin** [comment]
It seems like this should be solved, I'm closing this issue. Feel free to let us know if something else isn't working.
